### ISSUE TITLE
Agenda for 10/13/15

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#100]
- [ ] FCC Testing Update
- [ ] What to have ready for JQuery event this weekend
- [ ] Revisit action items from last week

**Comment by Frijol** [comment]
https://github.com/tessel/project/issues/95 jquery

**Comment by Frijol** [comment]
* [ ] Need to open source all technical-machine repos properly

**Comment by tcr** [comment]
https://github.com/tessel/project/blob/master/meetings/2015-10-13.md
