### ISSUE TITLE
Steering Committee Agenda 10/22/15

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#101]
- [x] Commercial Request for T2
- [x] New team members?

**Comment by tcr** [comment]
@johnnyman727 What kind of agenda?

**Comment by johnnyman727** [comment]
@tcr hidden

**Comment by johnnyman727** [comment]
- [ ] `node-usb`

**Comment by Frijol** [comment]
- [ ] Weigh in on controversial issue? https://github.com/tessel/t2-start/issues/55#issuecomment-149152317
- [ ] Devoting resources to fixing FCC: what can I do to help?
- [ ] Pushing out a TWIT: we need to do this! Include: recap from jQuery, new team members, Node 4, how to get involved without hardware, open sourcing of everything we have including the website

**Comment by Frijol** [comment]
- [ ] How do we reduce feature creep/focus as a team better? ie bikeshedding nvm, LED APIs, colored text in output - when core functionalities aren't there yet

**Comment by johnnyman727** [comment]
- [ ] Make milestone for Fullstack

**Comment by tcr** [comment]
@frijol on notes
@johnnyman727 moderating

**Comment by Frijol** [comment]
https://github.com/tessel/project/blob/master/meetings/2015-10-22.md

**Comment by Frijol** [comment]
https://github.com/tessel/this-week-in-tessel/issues/11
