### ISSUE TITLE
agenda 02/23/16

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#134]
moderator: @rwaldron 
notes: @tcr 

- [x] jQuery Foundation Concerns

**Comment by tcr** [comment]
- [ ] Last week's agenda https://github.com/tessel/project/blob/master/meetings/2016-02-17.md

**Comment by Frijol** [comment]
* [ ] Jon has an unsustainable workload
* [ ] Let's congratulate ourselves briefly on shipping some boards
* [ ] Note re inventory for events
* [ ] Thoughts/projections for finishing USB modules + tutorials

**Comment by Frijol** [comment]
* [ ] What can we tell people about shipping dates when they ask

**Comment by Frijol** [comment]
* [ ] Status of Seeed sending modules to us
* [ ] Status of Seeed putting their Tessel store up on the website
* [ ] Status of Seeed putting the modules they're missing up into their store

**Comment by johnnyman727** [comment]
Resolved with https://github.com/tessel/project/commit/4e0d29c13f34296d7ebf0dcbede9a16bb61473a4.
