### ISSUE TITLE
Tessel Reach

### ISSUE THREAD

**Issue by Frijol** [tessel/project#142]
We've discussed the idea of Tessel Reach as our next hardware. Making this issue as a place to develop on that idea.
## What is Tessel Reach?

Tessel Reach is a BLE-enabled low-power node. It breaks out a standard 10-pin Tessel module port and is meant to work in concert with a Tessel 2.

The point of Tessel Reach is to enable low-power internet-connected devices to be programmed in high-level languages - an extension of Tessel into the low-power realm, and a sensible/accessible way to connect many distributed sensor nodes to form a sensor ecosystem.

The Tessel 2 is meant to work as the hub of a star network whose points are Reach modules. The Tessel 2 is the main entry point for the programmer:
- Tessel 2 has Wifi & thus a connection with the internet
- Tessel 2 has high processing power and can be easily programmed with high-level languages
- You only need one Tessel 2 to control many BLE Reach nodes
- You would use a USB BLE dongle to enable Tessel 2 to work with Reach
- The Tessel 2 is probably plugged into a wall for long-term deployment

The Reach modules are low-power relatively "dumb" components:
- Each Reach module has a chip with BLE and low power/memory
- Reach modules receive their instructions over the [Gossip](https://github.com/tessel/reach) BLE protocol from the Tessel 2, pre-translated into low-level instructions
- Reach modules are most likely powered by a coin cell battery for months-years
## Is there hardware for this?

Yes! [This repo](https://github.com/tessel/reach-hardware) contains some functional hardware designs.
## What's the status of this project?

This is an idea we developed in early 2015 to the point of hardware and some of the software, but didn't have the bandwidth to develop in concert with Tessel 2. Here are the two main repos:
- [Hardware](https://github.com/tessel/reach-hardware)
- [Software](https://github.com/tessel/reach)

The software repo's Readme has a good overview of status in the Priorities section.

**Comment by rootscript** [comment]
I think that Tessel Reach would be very useful.  I ordered a similar project from kickstarter (a long time ago, but still haven't received it).  Here is a link to the [McThings project on kickstarter](https://www.kickstarter.com/projects/2016620887/mcthings-tiny-wireless-bluetooth-sensors-and-contr/description).

When I do receive the one I ordered from kickstarter, I will feed back to you guys, if you think it might be useful?

**Comment by tikurahul** [comment]
:eight_spoked_asterisk:  Gossip on BLE sounds amazing !

**Comment by Frijol** [comment]
Transferring over some discussion from https://github.com/tessel/this-week-in-tessel/pull/27:

from@mulderp:

> - As @HipsterBrown mentions, the ESP8266 is very popular in e.g. maker spaces to build connected setups. It might be worth to mention how/where the ESP8266 fits in a setup with Tessel 2
> - Also, Lorawan networks are coming up slowly (see e.g. the Things Network) - it might be interesting to mention that for communication with nodes between 1km - 5km, Lorawan might be interesting. Bluetooth is limited to a couple of meters only

from @johnnyman727:

> Good points @mulderp. My feelings on the matter:
> 
> > It might be worth to mention how/where the ESP8266 fits in a setup with Tessel 2
> 
> I don't have a good answer to this. I like BLE more because it's lower power and I recall that there were plans to make it interoperable with IPv6. I haven't been staying up-to-date on that effort so I'm not sure of its progress. It's also lower friction, IMO, to connect to a BLE device than a WiFI network and the work of The Physical Web builds upon that. 
> 
> > for communication with nodes between 1km - 5km, Lorawan might be interesting. 
> 
> Agreed, but I've seen more pull on BLE than long distance networks. Could be a good T2 module or future board though.

from @EvanSimpson:

> @johnnyman727 I don't know that IPv6 has worked its way into the official standard, but I know [Nordic has a stack for it](http://www.nordicsemi.com/eng/News/News-releases/Product-Related-News/Nordic-Semiconductor-IPv6-over-Bluetooth-Smart-protocol-stack-for-nRF51-Series-SoCs-enables-small-low-cost-ultra-low-power-Internet-of-Things-applications), probably proprietary. 
> 
> The distance is also going to increase significantly in the next couple years as [Bluetooth 5](https://www.bluetooth.com/news/pressreleases/2016/06/16/-bluetooth5-quadruples-rangedoubles-speedincreases-data-broadcasting-capacity-by-800) rolls out and becomes available on cheap hardware.
> 
> I think one thing to consider with BLE vs. WiFi/ZigBee/etc. is the direct interoperability with smart phones and BLE capable computers. It enables Reach to be a development platform independent of Tessel or any other prototyping hardware.

**Comment by nodebotanist** [comment]
So I've been doing research on the ESP32 and BLE. I'll present more info at the meeting, but I think the ESP32 would be a good choice-- we could allow wifi reach mode as well as BLE, and there is some interesting work on nodeMCU that could come in handy.

**Comment by tcr** [comment]
Closing this thread. All discussion is moved over to http://github.com/tessel/reach-wg
