### ISSUE TITLE
Agenda 4/19/16

### ISSUE THREAD

**Issue by Frijol** [tessel/project#148]
Moderator: @johnnyman727 
Notes: @frijol

- [x] Thoughts on keeping our own stock at Whiplash? (get a bulk amount shipped from Seeed at relatively low cost, be able to access it quickly when needed) (minor additional discussion: want to do anything with USB modules?)
- [x] Check back on action items from [last week](https://github.com/tessel/project/blob/master/meetings/2016-04-12.md)
- [x] Current most important issues to triage?
- [x] Team members?

**Comment by Frijol** [comment]
* [ ] Review our install instructions for various OS's (@johnnyman727)

**Comment by Frijol** [comment]
* [ ] hoodies

**Comment by Frijol** [comment]
* [ ] https://github.com/tessel/tessel.io/issues/67

**Comment by tcr** [comment]
* [ ] windows
* [ ] telec

**Comment by Frijol** [comment]
* [ ] clear enough that T1 modules on Seeed page shouldn't go with T2?
