### ISSUE TITLE
Steering Committee Meeting 4/26/16

### ISSUE THREAD

**Issue by Frijol** [tessel/project#150]
Moderator: @tcr 
Notes: @johnnyman727 

* [ ] Check in on last week's action items
* [ ] Updates on most urgent issues

**Comment by Frijol** [comment]
* [ ] Talk about what's next for us as an org, our individual commitment, etc.

**Comment by rwaldron** [comment]
- [ ] new team members

**Comment by Student007** [comment]
> Would be great to get a champion of installs who could set up CI to ensure installation works on various platforms (anyone reading these notes: interested in taking this on?)

@Frijol well, I feel like I did [this work](https://github.com/Student007/t2-reference-VMs) for nothing :wink:

**Comment by wyze** [comment]
- [ ] Labels for Issues/PRs. Labels are better than the tags (e.g. [list], [run]) that way issues/PRs can be filtered by labels. Specific to the CLI project, this would help a lot, and each command would have it's own label. Just more label use in general. :)
