### ISSUE TITLE
Implement issue labels for all active repos

### ISSUE THREAD

**Issue by rwaldron** [tessel/project#152]
I've specified "active" as a qualifier only to give a clean starting point... because there are a lot of repos :)

**Comment by wyze** [comment]
I think just looking under the organization (https://github.com/tessel) we can get a pretty accurate representation of what is "active". I'll give these some thought over the next couple of days and have a follow up comment that I will keep updated for feedback/discussion.

**Comment by Frijol** [comment]
Moving discussion over from #165, @HipsterBrown and I were discussing this yesterday re how to make it easier for contributors to get involved.

I believe @HipsterBrown made a list of labels and was working on a draft for defining them in the tessel/project readme.

**Comment by Frijol** [comment]
prototyping standard labels over on t2-cli: https://github.com/tessel/t2-cli/labels

![screen shot 2016-09-02 at 2 20 16 pm](https://cloud.githubusercontent.com/assets/454690/18213908/6b2be2ec-7118-11e6-89a3-c215e7702374.png)

**Comment by Frijol** [comment]
ok, I think I did it. I implemented all of the above-pictured labels on all the active repos where reasonable. I also have a "design" tag, which you can see on the tessel.io repo

:phew:

**Comment by tcr** [comment]
👏
