### ISSUE TITLE
SC Agenda 5/18/16

### ISSUE THREAD

**Issue by tcr** [tessel/project#157]
Moderator: @rwaldron
Notes: @frijol

* [x] Discuss Reach vs. Fractal
* [x] Need to put out a new blog post: https://github.com/tessel/this-week-in-tessel/issues/19
* [x] thoughts on https://opencollective.com/opensource?

**Comment by Frijol** [comment]
* [ ] Anything we've heard from Seeed lately? (@johnnyman727)
* [ ] Should I move forward with making t2-docs a gitbook?

**Comment by Frijol** [comment]
* [ ] Other language support

**Comment by Frijol** [comment]
* [ ] FINANCES.md

**Comment by Frijol** [comment]
resolved with https://github.com/tessel/project/issues/157
