### ISSUE TITLE
Define a process for feature proposals (RFCs)

### ISSUE THREAD

**Issue by tcr** [tessel/project#16]
We mention RFCs in the guidelines. I seek input on these items:

* Do we need a formalized process, or even unformal RFC form?
* What is the intent of RFCs with regard to how it connects the community to decision-makers?

**Comment by tcr** [comment]
My proposal from that:

* All feature proposals are forked from a tessel/rfcs repo (this is the rust model)
* All issue discussion and PRs can happen on that forked repo itself. E.g. tessel/rfcs -> tcr/wifi-rfc, that's the source for discussion
* We only have two stages, for simplicity; pre-merge and post-merge. Issues should be brought up on the PR into tessel/rfcs, but handled on the original repo

Rest is similar. Will post a more formalized suggested process post-SC meeting

**Comment by rwaldron** [comment]
> My only suggestion would be that we encourage folks making these RFCs to post a link on the Forums to include as many people as possible. @tcr @Frijol what are your thoughts?

Yes, champions should do their best to build support for a feature proposal in any way that they can :)

@tcr 

> All feature proposals are forked from a tessel/rfcs repo (this is the rust model)
> All issue discussion and PRs can happen on that forked repo itself. E.g. tessel/rfcs -> tcr/wifi-rfc, that's the source for discussion
> We only have two stages, for simplicity; pre-merge and post-merge. Issues should be brought up on the PR into tessel/rfcs, but handled on the original repo

+1  to all (the number of stages irrelevant, just that the stages are well defined)

**Comment by johnnyman727** [comment]
Codified into https://github.com/tessel/rfcs/pull/1.
