### ISSUE TITLE
Tesselcamp New York September 1-3 2016

### ISSUE THREAD

**Issue by Frijol** [tessel/project#179]
## When & where?
New York City, September 1-3

### Sept 1&2: [61 Local in Brooklyn](https://goo.gl/maps/uidtWX7h47m) (Thurs/Fri)
* 10am-12pm Steering Committee
* 12pm-6pm SC + Team Members

### Sept 3: Saturday at [WeWork Times Square](https://v2.wework.com/locations/new-york-city/times-square) – please [RSVP](http://www.meetup.com/nodebots/events/233568320/)!
* 11am-6pm Public welcome! "Welcome, let us help you become contributors" day. We would like to help anyone who is interested in the project feel comfortable working within the community/on hardware/in editorial roles. New programmers particularly welcome, we are happy to mentor people getting into open source.

## What is it?

Time & space for people to contribute to the Tessel Project. The basic objectives:

* Have face-to-face meeting time to work out the roadmap for our next projects
* Help people get involved and contributing
* Take some time to hang out and work on the project together

## What isn't it?

A conference, party, or actual camping trip (this time). It's simple, it's small, it's not something we're planning to sell tickets to or broadly advertise. There might not be any food, drinks, swag, or budget, because that's not the point.

## How big is it?

Small. Attendance cap ~20 people probably. Includes all Steering Committee members, any Team Members who can make it, and then anyone who's interested in getting involved (assuming there is still space).

## What specifically are we going to do?

Good question. Submit ideas to this issue!

cc @rwaldron @HipsterBrown @tcr @johnnyman727

**Comment by tikurahul** [comment]
This sounds amazing. Do you have probable dates yet ? Would love to attend if possible.

**Comment by Frijol** [comment]
Most likely August 25-27 or September 1-3. Hope you can join us @tikurahul!

**Comment by tikurahul** [comment]
I can make it if its Sept 1-3. I have another event on Aug 25-27 :cry:

**Comment by flaki** [comment]
I think I can make Sept 1-3, too :) (and practically the only reason I'm stating this in a lengthy comment is to subscribe to e-mails on this issue 😁)

**Comment by nodebotanist** [comment]
Interested. Will look into getting there.

**Comment by Frijol** [comment]
Update:
* Confirmed Sept 1-3
* Looking into venues, will update on that
* Format: Thursday & Friday, we will have a space where Team Members can hang out & hack together all afternoon, with some scheduled time to meet and discuss things on the agenda (see next point). Saturday, we will do an open-community hack where we work with members of the community on getting started & getting involved. Also some J5IK's to play with.
* Agenda: please propose discussion points here! For example:

* [ ] Agenda: How do we better triage issues and maintain repos such that nothing gets lost or crusty/old?

**Comment by Frijol** [comment]
Update for everybody: I added some logistics to the top :)

**Comment by Frijol** [comment]
Agenda items transfered from SC meeting https://github.com/tessel/project/blob/master/meetings/2016-08-23.md

@tcr SC: Reach and new hardware
@frijol Team Members: Discuss what are most annoying bugs to triage (bountiful days)
@rwaldron Reproduce and eliminate duplicate messages bug
@tcr Rust plan for T2
@hipsterbrown tessel.io redesign + bringing in contributors
@johnnyman727 Test Rig: documentation + handoff (maybe...)
Diversity in contributors and members — incl. outreach to new groups (FullStack, Grace Hopper)

**Comment by johnnyman727** [comment]
It's worth noting that @rwaldron's request is likely resolved via https://github.com/tessel/t2-firmware/pull/204.
