### ISSUE TITLE
Newsletter contains references to technical machine in footer

### ISSUE THREAD

**Issue by boneskull** [tessel/project#180]
Let me know if you need a screenshot or whatever.

**Comment by Frijol** [comment]
thanks - been meaning to fix that!

**Comment by Frijol** [comment]
![screen shot 2016-07-02 at 10 24 54 am](https://cloud.githubusercontent.com/assets/454690/16539310/3f99245a-403f-11e6-966d-7bee97fadfd1.png)

fixed! (finally)

cc @ekolker for also pointing this out to me

**Comment by Frijol** [comment]
heh, whoops, fixed our template to point to the right twitter account too
