### ISSUE TITLE
Agenda for 2016-07-19

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/project#187]
## Last Week's Action Items

- [ ] @rwaldron & @hipsterbrown draft an ISSUE_TEMPLATE.md for t2-cli repo [ported to next week]
- [x] @hipsterbrown follow up with @reconbot re deployment, maybe gitbooks.io with redirect? also @frijol
- [x] @hipsterbrown draft a Google form getting community research re Reach needs
- [x] @tcr Add hoodies shipping info to Whiplash
- [x] @tcr document TELEC testing in public gist
- [x] @tcr email MailChimp about free service
- [x] @johnnyman727 post the Rust getting-started gist to the blog
- [x] @johnnyman727 write up something about multiple language support plugin for public knowledge
- [x] @frijol investigate if there is someone who might be interested in championing Reach
- [x] @johnnyman727 message @reconbot about Sparkfun/Italian manufacturer discussion
- [x] @johnnyman727 talk to Jory about potential upsides/downsides to exclusivity in new contract negotiations
- [x] @johnnyman727 update issues surrounding button API in firmware and docs
- [x] @johnnyman727 check with Jia on why analog values are mapped 0-3.3 instead of 0-1

## New Items

- [x] RFC process
- [x] TesselCamp schedule / activities 
- [ ] [Issue triage](http://crash-reporter.tessel.io/trending) [ported to next week]

**Comment by Frijol** [comment]
* [ ] Tim help me get a not-corrupted SVG logo?

**Comment by tcr** [comment]
@frijol this work? (rename to `tessel-logo.svg`)
[tessel-logo.txt](https://github.com/tessel/project/files/372154/tessel-logo.txt)

**Comment by Frijol** [comment]
* [ ] Drafted July TWIT, anything important missing? Anyone want to write the Nodebots Day section? https://github.com/tessel/this-week-in-tessel/pull/33

**Comment by tcr** [comment]
Merged.
