### ISSUE TITLE
Add unmaintained warning to old repos

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#196]
## Definitely unmaintained
- testalator-device
- vclib
- tessel-build
- tm-eagle-library
- hardware-resolve
- ir-codes
- continuous (also, let's rename to t1-continuous)
- rf-nrf24
- ptp-hw-raspibplus
- colony-lua
- tessel-wifi-tests
- hsregex
- 6LoWPAN-module
- neopixels
- cloud
- runtime-qemu
- wifi-cc3000
- sink_q
- 6LoWPAN-target
- smm
- c-ares
- cc3000-spy
- jobserver
- colony-compiler
- proxy
- oauth
- camera-vc0706
- gprs-sim900
- t1-contribution-guide
- tessel-node-red
- t1-modules-kicad
- audio-vs1053b
- ble-ble113a
- playground
- hardware
- t1-firmware
- t1-cli
- climate-si7005
- sdcard
- t1-runtime

## Maybe unmaintained
- vcd (up to @tcr)
- ppps (up to @tcr)
- tessel-python

## Just delete
- jsconf
- module-test-benches (it's just a conglomeration of all the module tests)
- portal-beta (an early version of the forums for Technical Machine)
- style (a style guide for the Technical Machine)

**Comment by johnnyman727** [comment]
All modules marked as "to be deleted" or "to be deprecated" have been taken care of.

All that's left is @tcr to transfer `vcd`, `ppps`, and `tessel-python` to his personal account.

**Comment by tcr** [comment]
@johnnyman727 Done.

**Comment by johnnyman727** [comment]
👻
