### ISSUE TITLE
What tools will allow us to collaborate in a distributed, asynchronous environment?

### ISSUE THREAD

**Issue by tcr** [tessel/project#20]
Is collaboration on in-depth tasks (debugging, design, or community) best accomplished using the tools we have? Some combination of our channels:

* IRC
* Forums
* Hangouts
* Trello
* Github Issues.

For collaborating and development, we've historically used Zulip, which is not public.

**Comment by johnnyman727** [comment]
For the record, we are using [Slack for chatting](http://tessel-slack.herokuapp.com/) and Github Issues for most asyncronous communication related to development. We also use [the Forums](forums.tessel.io) for support.
