### ISSUE TITLE
Standard In-person Onboarding

### ISSUE THREAD

**Issue by Frijol** [tessel/project#202]
_From @johnnyman727 on September 1, 2015 4:58_

Let's create a process for our one-on-one calls to get a new Team Member up to speed. In the past, I've gone over the following things (generally, in this order):
- How to update your Tessel
- Blinky (t2 init and t2 run)
- Who is working on what
- Biggest outstanding bugs that can trip you up
- That leads into walking through the issues and picking out one that's a good fit to start with
- Talking about how they might go about solving that issue and who they can go to for help
- Quick introduction to Slack if unfamiliar
- How to get in touch with me

@Frijol @rwaldron what has your process been so far?

_Copied from original issue: tessel/onboarding#6_

**Comment by Frijol** [comment]
Oh I like the Blinky step

Ideally I would have them run through t2-start and then intro them to the CLI and firmware repos and have them try updating to dev versions.

As is, it's a little scattered. I basically run people through https://github.com/tessel/onboarding which I've updated to match any parts I saw missing.

Also:

* Ask why they want to be a part of the project/what pieces of it excite them
* Mention any major bugs I know about so they don't trip on them
* Find an issue to work on
* If we run into issues, ask on Slack to get started using the community as a resource
* Intro to Slack, join #engineering and #team-members, probably also #events-speaking

Things I'd like to add in:

* Something to do with the mission & core philosophies
* Intro to the blog ("and you can write for it")

Would be worthwhile also to think about onboarding experiences to fit e.g. people excited about organizing events, writing docs, working on hardware

**Comment by Frijol** [comment]
_From @johnnyman727 on September 4, 2015 6:40_

I do like the `t2-start` guide and introducing them to Slack. I agree that those should be part of the process.

The blog is interesting because I think some people will really go for it and some people really won't. I suppose it's worth gauging interest.

I think if they are already selected to be a team member then they probably understand the core mission, right? Perhaps it's worth briefly stating?

**Comment by Frijol** [comment]
Re mission statement/core philosophies, it might be worth referencing briefly in the onboarding repo. The Core Philosophies have some practical value that might help contributors

**Comment by Frijol** [comment]
@johnnyman727 @HipsterBrown @tcr @rwaldron I am deprecating this "onboarding" repo because everything that is here can belong elsewhere. I think this discussion should lead to something on the tessel/project repo. What would you like to see it become?

**Comment by johnnyman727** [comment]
Maybe an `onboarding-tips.md` doc in this repo?

**Comment by Frijol** [comment]
This is largely covered in TEAM-MEMBERS.md in this repo.
