### ISSUE TITLE
SC Agenda 10/4/16

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/project#216]
**Moderator:** @Frijol 
**note-taker:** @rwaldron 

## Last Week's Action Items:

- [x] @johnnyman727 Send Seeed device to Rick
- [x] @rwaldron Follow up with Jory about next meeting
- [ ] @hipsterbrown Draft/write a Captive Portal RFC. (kicked to next week)
- [ ] @hipsterbrown Recruit people for Tessel.io redesign
- [x] @frijol Tell us Tales from the Storage Locker. Acquire Reach.
- [x] @frijol Test out Accelerometer docs.
- [x] @frijol, @hipsterbrown Schedule meetings with new team members. Add to TEAM-MEMBERS.md
- [x] @frijol Place new orders for stickers
- [x] @frijol Organize Learning WG
- [ ] @tcr #engineering discussion about Tessel II
- [x] @tcr Acquire Reach from Kolker.
- [ ] @tcr "Meet a Tesseler" about yourself.
- [x] @tcr Post Reach specification draft to WG
- [ ] @tcr TELEC testing
- [x] @tcr Send it out TWIT demo
- [x] @tcr Add SendInBlue to Passopolis, add information to this-week-in-tessel README
- [x] @tcr Add signup process to website

## Agenda:

- Hacktoberfest

**Comment by Frijol** [comment]
* [ ] Jia's Reach board
* [ ] Srsly let's get working groups going

**Comment by tcr** [comment]
* [ ] Rust update

**Comment by rwaldron** [comment]
- [ ] Seeed device report (so far)
- [x] Reach, but I don't have the points that I need

**Comment by Frijol** [comment]
* [ ] Update Reach issue
