### ISSUE TITLE
Agenda 2016-11-08

### ISSUE THREAD

**Issue by rwaldron** [tessel/project#222]
Moderator: @HipsterBrown \
Notes: @rwaldron \
Attending: @tcr

## Last Week

https://github.com/tessel/project/blob/master/meetings/2016-11-01.md

- [ ] @tcr Rust Blog Post announcements
- [ ] @hipsterbrown Captive portal + AP updates
- [ ] @hipsterbrown Follow up on Hacktoberfest
- [ ] @tcr Document the firmware build process
- [ ] @tcr Ping users about Bus Blaster SWD probing script
- [ ] @all IoT security blog post research, ideas, suggestion

## This Week

- [ ] Can we get Seeed to refund accidental orders for T1 camera module? https://github.com/tessel/tessel-av/issues/17
- [ ] EmpireNode recap

**Comment by HipsterBrown** [comment]
Closed by https://github.com/tessel/project/blob/master/meetings/2016-11-08.md
