### ISSUE TITLE
SC Agenda Dec 13 2016

### ISSUE THREAD

**Issue by Frijol** [tessel/project#227]
**Moderator:** @frijol
**Note-taker:** @tcr 

## Agenda

* [x] Last week's action items
* [x] Path for getting custom/stripped-down Tessels?
* [x] [RailsGirls Summer of Code](http://railsgirlssummerofcode.org/)
* [x] Check in on WG progress

**Comment by rwaldron** [comment]
- [ ] Upgrading openwrt? https://github.com/tessel/openwrt-tessel/pull/68#issuecomment-266751644

**Comment by tcr** [comment]
Meeting notes posted.
