### ISSUE TITLE
SC Agenda 2017-01-11

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/project#234]
Moderator: @frijol
Notes: @rwaldron

# Agenda 

- [x] [Last week's items](https://github.com/tessel/project/blob/master/meetings/2017-01-04.md#action-items)
- [x] Tessel modules & Seeed
- [x] Kelsey's share & tell

**Comment by Frijol** [comment]
Notes are https://github.com/tessel/project/blob/master/meetings/2017-01-11.md
