### ISSUE TITLE
Shrinking server and mail server use

### ISSUE THREAD

**Issue by tcr** [tessel/project#24]
Currently we have many legacy servers from Technical Machine. These should be trimmed down for the Tessel Project.

@HarleyKwyn put together this list of servers we are currently using:

| Purpose | Provider | host-name | monthly cost |
| --- | --- | --- | --- |
| storefront | digital ocean | shop.tessel.io | $5 |
| rampart | digital ocean | rampart.tessel.io | $5 |
| whiplash | digital ocean | ??? | $5 |
| projects portal | digital ocean | projects.tessel.io | $5 |
| forums | digital ocean | forums.tessel.io | $20 |
| tessel.io | heroku | technical-io. | $34.50 |
| start.tessel.io | heroku | start.tessel.io | $20.00 |
| stage | heroku | techinical-io-stage.tessel.io | $0 |
| email | google | n/a | $80 |
|  |  | total | $174.50 |

Goals:

| Purpose | Provider | host-name | monthly cost |
| --- | --- | --- | --- |
| tessel.io | digital ocean | tessel.io | $20.00 |
| rampart |  | rampart.tessel.io | ^^^ |
| start.tessel.io |  | start.tessel.io | ^^^ |
| stage |  | stage.tessel.io | ^^^ |
| forums | digital ocean | forums.tessel.io | $20 |
| email | fastmail | n/a | ~$10 ($15/year per user) |
|  |  | total | $50 |

Sunsetting:

| Purpose | Provider | host-name | monthly cost |
| --- | --- | --- | --- |
| storefront | digital ocean | shop.tessel.io | redirect |
| whiplash | digital ocean | ??? | offline |
| projects portal | digital ocean | projects.tessel.io | offline |

**Comment by Frijol** [comment]
status of this @tcr @HarleyKwyn ? Did this happen?

**Comment by HarleyKwyn** [comment]
Yeah were are we with this? I'm willing to give a dokku box another try but not sure how much we'll get for it. I still see we're using heroku which is costing us $34.50 a month now because of the SSL end point.

**Comment by Frijol** [comment]
resolved, @tcr ?

**Comment by LinusU** [comment]
@HarleyKwyn [Let's Encrypt](https://letsencrypt.org) is in public beta if you want free SSL certificates.

**Comment by tcr** [comment]
We've transitioned successfully to mostly free infrastructure + donations from Digital Ocean. See https://github.com/tessel/project/blob/master/WWW.md for more details.
