### ISSUE TITLE
SC Meeting for Feb 14, 2017

### ISSUE THREAD

**Issue by tcr** [tessel/project#245]
**Moderator:** @tcr
**Notetaker:** @HipsterBrown 
**Attending:** @Frijol 

## Agenda

* [Last week's action items](https://github.com/tessel/project/blob/master/meetings/2017-02-07.md)
* Seeed updates
* Working group updates
   * Reach
   * Rust
   * Website
   * Production

**Comment by Frijol** [comment]
* Producing a header-less Tessel for people considering T2 for production
