### ISSUE TITLE
SC Meeting for Mar 28, 2017

### ISSUE THREAD

**Issue by tcr** [tessel/project#257]
**Moderator:** @tcr   
**Notetaker:** @HipsterBrown
**Attending:** @rwaldron, @frijol

## Agenda

* [Last week's action items](https://github.com/tessel/project/blob/master/meetings/2017-03-21.md)
* Moving off of Heroku 
* Working group updates

**Comment by Frijol** [comment]
Better way to recognize first-time contributors?
