### ISSUE TITLE
Switch from Mitro to Lastpass

### ISSUE THREAD

**Issue by tcr** [tessel/project#266]
We should leave Mitro, it being basically unmaintained. My preferred option would be LastPass; it's maintained, used in large and small companies, and offers what we'd need cheaply:

1. We create a Tessel LastPass account upgraded to Premium, $12 / year.
1. We create a Shared Family Folder with all the Mitro passwords.
1. We share that folder with all of our personal accounts. I have a Premium LastPass account, but it should work with free accounts just as well.
1. We delete our old Mitro account and extension, and install the LastPass extension instead.

**Comment by tikurahul** [comment]
Maybe look at 1Password too. It's really excellent, and had a great Web UI. Also $5 a month.

**Comment by Frijol** [comment]
To be clear, Mitro == Passopolis?

**Comment by tcr** [comment]
We transitioned a few months back to LastPass.
