### ISSUE TITLE
Contributing Guide needs improvement

### ISSUE THREAD

**Issue by Frijol** [tessel/project#27]
Related to many of the ideas in https://github.com/technicalmachine/tessel-project/issues/15 ([Current guide](https://github.com/technicalmachine/tessel-project/blob/master/CONTRIBUTING.md))

**Comment by bryan-m-hughes** [comment]
A little late to the party, but if you check out the io.js [contributing guide](https://github.com/nodejs/io.js/blob/master/CONTRIBUTING.md) (vs their collaborating guide), they do have a brief CoC. Something to consider adding.

**Comment by Frijol** [comment]
We have a CoC and I thought we had a link to it in the contributing guide but I don't see it now... thanks for bringing that up, def need to add that back in
