### ISSUE TITLE
Consider using Greenkeeper to keep dependencies up to date

### ISSUE THREAD

**Issue by Frijol** [tessel/project#270]
https://greenkeeper.io/

**Comment by tcr** [comment]
👍

**Comment by Frijol** [comment]
Giving it a shot on t2-cli

**Comment by Frijol** [comment]
https://github.com/tessel/t2-cli/tree/greenkeeper%2Finitial it just auto-made this branch. Not thrilled that it put its badge on a newline, but not sure how it would do that differently automatically

**Comment by Frijol** [comment]
And a PR! https://github.com/tessel/t2-cli/pull/1305

**Comment by Frijol** [comment]
Discussion underway in https://github.com/tessel/t2-cli/pull/1305
