### ISSUE TITLE
SC Meeting for May 22, 2017

### ISSUE THREAD

**Issue by tcr** [tessel/project#287]
**Moderator:** @rwaldron 
**Notetaker:** @Frijol 
**Attending:** @tcr @HipsterBrown 

## Agenda

* [Last week's action items](https://github.com/tessel/project/blob/master/meetings/2017-05-16.md)
* Better surfacing how frequently/actively we update T2
* Working group updates
* LEDE 17 migration

**Comment by Frijol** [comment]
* TWIT
* Discussion around support weeks https://github.com/tessel/project/issues/281
