### ISSUE TITLE
SC Meeting for Jun 7, 2017

### ISSUE THREAD

**Issue by tcr** [tessel/project#290]
(This is an automatic template, fill in below)

**Moderator:** ???  
**Notetaker:** ???  
**Attending:** ???  

## Agenda

* Last week's action items
* Working group updates
* ???
* ???

**Comment by Frijol** [comment]
* Last week's stuff, punted: https://github.com/tessel/project/issues/289
* produce info from internship mentoring at Technical Machine to use for mentorship within the Tessel Project

**Comment by tcr** [comment]
https://github.com/tessel/project/blob/master/meetings/2017-06-07.md
