### ISSUE TITLE
3G module - how to use?

### ISSUE THREAD

**Issue by aquaminer** [tessel/project#300]
![chrome_2017-07-24_08-49-55](https://user-images.githubusercontent.com/17113289/28509805-14e03b24-704d-11e7-8587-bc346d82aa38.png) how to use?

**Comment by Frijol** [comment]
@HipsterBrown @tcr where is the best place to look for the progress on this?

**Comment by HipsterBrown** [comment]
Probably this issue -> https://github.com/tessel/t2-cli/issues/541
