### ISSUE TITLE
'getRandomBytes' error for BME tutorial

### ISSUE THREAD

**Issue by apekearo** [tessel/project#347]
Hello,  I've been trying to get the BME experiment to work on my new Tessel 2,
https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit/experiment-10-using-the-bme280
and i keep getting an error, even though I've tried all sorts of changes, same error everytime.
TypeError: Cannot set property 'getRandomBytes' of undefined
    at Object.<anonymous> (/tmp/remote-script/node_modules/base64id/lib/base64id.js:1:122)

I'm not sure what else i can try to figure it out,   there's not a lot of documentation about this error.  I figure I'm calling the api the wrong way, but its looking fine for me on my end.  I'm using the code snippets from the link i mentioned.  If you have any advice, I could use it.  I really want this feature to get working.  Thank You!

**Comment by rwaldron** [comment]
Thanks for filing an issue, but this repo is for Tessel project documents and administrative stuff :\ This issue is likely caused by unsafe compression rules in uglify-es. I will add the base64id module to the black list and get a release of t2-cli out.
