### ISSUE TITLE
SC Meeting for Thu, Oct 12th, 2017

### ISSUE THREAD

**Issue by tcr** [tessel/project#348]
**Moderator:** @rwaldron  
**Notetaker:** @HipsterBrown
**Attending:** @Frijol  

<details>
<summary>Links for moderators</summary>

* [Edit link for meeting notes.](https://github.com/tessel/project/edit/sc-agenda-348/meetings/2017-10-12.md)
* [Meeting notes once they've been posted.](https://github.com/tessel/project/blob/master/meetings/2017-10-12.md)
* Previous agenda: #343
</details>

## Agenda

* [x] [Last week's action items](https://github.com/tessel/project/blob/master/meetings/2017-10-12.md)
* [ ] `scbot` lives!
* [x] TesselCamp

**Comment by tcr** [comment]
#scbot update today

**Comment by tcr** [comment]
#scbot add `scbot` lives!

**Comment by tcr** [comment]
#scbot add TesselCamp

**Comment by tcr** [comment]
#scbot add test

**Comment by tcr** [comment]
#scbot update next thursday

**Comment by Frijol** [comment]
damn you scbot
