### ISSUE TITLE
SC Meeting for Thu, Nov 16th, 2017

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/project#353]
**Moderator:** @Frijol 
**Notetaker:** @tcr

<details>
<summary>Links for moderators</summary>

* [Meeting notes once they've been posted.](https://github.com/tessel/project/blob/master/meetings/2017-11-16.md)
* Previous agenda: #348
</details>

## Agenda

* [ ] [Last week's action items](https://github.com/tessel/project/blob/master/meetings/2017-10-19.md)

**Comment by tcr** [comment]
#scbot update today
