### ISSUE TITLE
t2 restore stocks in Writing OpenWRT SquashFS...

### ISSUE THREAD

**Issue by ivanyosef** [tessel/project#354]
Hi, i am trying to restore my tessel 2 but every time i try, it gets stock in some percent at Writing OpenWRT SquashFS

Here is the output for t2 restore

INFO Looking for your Tessel...
INFO Connected to your Tessel.
INFO Downloading files...
INFO Download complete!
INFO Restoring your Tessel...
INFO Bulk Erasing Flash Memory (this may take a minute)...
INFO Writing U-Boot...
INFO Writing MediaTek factory partition...
INFO Writing OpenWRT SquashFS...
     [==                          ] 10% 35.5s remaining

I also try t2 restore -f , but does not work :(, what can i do??? i really need help, i can not get into the forums :(  thanks

**Comment by rwaldron** [comment]
After it gets stuck, what happens when you unplug it, plug it back in and run `t2 list` (after it finishes booting)?

**Comment by Frijol** [comment]
Closed due to inactivity
