### ISSUE TITLE
New Contribution

### ISSUE THREAD

**Issue by reshusinghhh** [tessel/project#364]
I am new to the open source contribution.I have earlier know about ESP32 chip.
How can we contribute for hardware part on opensource platform?Do help.

**Comment by Frijol** [comment]
Hi, and welcome! [This link](https://github.com/tessel/reach-wg#what-were-working-on-and-how-you-can-help) is probably the most useful place you can go to find out what to work on with the ESP32.

You may also wish to join our Slack channel to chat with us. That way, you can send us questions as you work, or tell us more about your skills so we can better match you to specific projects to work on. You can send your email to https://twitter.com/tesselproject in a direct message and we will add you to the Slack.
