### ISSUE TITLE
SC Meeting for Mon, Feb 12th, 2018

### ISSUE THREAD

**Issue by tcr** [tessel/project#372]
**Moderator:** @frijol  
**Notetaker:** @tcr   
**Attending:** @HipsterBrown   

<details>
<summary>Links for moderators</summary>

* [Edit link for meeting notes.](https://github.com/tessel/project/edit/sc-agenda-372/meetings/2018-02-12.md)
* [Meeting notes once they've been posted.](https://github.com/tessel/project/blob/master/meetings/2018-02-12.md)
* Previous agenda: #362
</details>

## Agenda

* [ ] Last week's action items
* [ ] Can we set dates for Tesselcamp?
* [ ] CodeTriage– any discussion? Please read https://github.com/tessel/t2-cli/pull/1406
* [ ] Recap from Sunday work session
* [ ] Infrastructure issues (Slack & Forums)– how do we fix so it's not a problem in the future?
* [ ] Upgrading Node version
* [ ] Status of static website for tessel.io
* [ ] Re-label contribution-starter? See https://github.com/tessel/project/issues/371
* [ ] Check in on current project priorities

**Comment by Frijol** [comment]
oh I made this one though https://github.com/tessel/project/issues/365

**Comment by tcr** [comment]
@Frijol Moved your action items over if that's okay :(

**Comment by Frijol** [comment]
#scbot help

**Comment by tcr** [comment]
#scbot schedule next monday @HipsterBrown @Frijol @tcr
