### ISSUE TITLE
ECMAScript Version?

### ISSUE THREAD

**Issue by crumdev** [tessel/project#385]
What version of ECMAScript does Tessel boards support? Can I use the newer features of javascript like const, let, classes etc?

**Comment by Frijol** [comment]
Tessel runs vanilla LTS Node on a Linux SoC (https://tessel.gitbooks.io/t2-docs/content/API/Supported_Languages.html). Short answer is: yes, I believe so! Here are some examples using `const` https://tessel.gitbooks.io/t2-docs/content/Tutorials/Communication_Protocols.html

**Comment by crumdev** [comment]
Thanks @Frijol
