### ISSUE TITLE
A beginners guide to using git

### ISSUE THREAD

**Issue by ShashwathJS** [tessel/project#387]
The following article is a reference to start off using git :
https://www.digitalocean.com/community/tutorials/how-to-use-git-a-reference-guide

**Comment by Frijol** [comment]
Hi @ShashwathJS thanks for your interest in contributing to the Tessel Project! Can you please explain more what problems you're identifying (specific to our project) with this issue and https://github.com/tessel/project/issues/389 ?

**Comment by ShashwathJS** [comment]
Hi @Frijol, I wasn’t addressing any specific issue in particular. Being new to the open source community I found this article useful for beginners like me to understand how to use git so that we can contribute to projects such as tessel
