### ISSUE TITLE
tessel.io is down

### ISSUE THREAD

**Issue by kaefer3000** [tessel/project#398]
Hi,

I wanted to check what's going on with the project and found that the website http://tessel.io/ is unavailable (also its HTTPS flavour).

Sadly I found here that the project seems quite dormant.

I liked hacking with the Tessel a lot (and so did my students), so it would be great if at least things continued to work and were available, even if no new things are being added.

Cheers!

Tobias

**Comment by abdullahfarwees** [comment]
Site is Still down 
![Screenshot_20230815-190652_Chrome](https://github.com/tessel/project/assets/11908787/fe970706-e30c-413c-b45b-7a697dde22b0)
