### ISSUE TITLE
discussion: current status of the project

### ISSUE THREAD

**Issue by abdullahfarwees** [tessel/project#400]
It would be great if the current status of the project is updated in the Readme file. This will helpful for the new visiters of the Github project page.

**Comment by Frijol** [comment]
Thanks for noticing! We haven't had the capacity to maintain properly in some years, though fwiw my tessel still seems to work fine. You are welcome to submit a PR noting the current unmaintained status of the project.

**Comment by abdullahfarwees** [comment]
@Frijol Please review the updated readme file and share your feedback.

1. Removed invalid links.
2. Updated current status of the project

covering Issue 
https://github.com/tessel/project/issues/400
https://github.com/tessel/project/issues/399 
https://github.com/tessel/project/issues/398
