### ISSUE TITLE
Rename "Technical Machine" things to Tessel

### ISSUE THREAD

**Issue by Frijol** [tessel/project#45]
* [x] technicalmachineblog tumblr
* [x] our name on twitter
* [x] our twitter handle?
* [x] FB page(s) - there's a Tessel and a Technical Machine and the Technical Machine one is much bigger
* [x] G+ group? There's a Tessel and a Technical Machine, and the Tessel one is much bigger
* [x] look over the website, I think About, Contact, Press, and copyright all have Technical Machine in them
* [x] anything else?
* [x] Pinterest https://www.pinterest.com/technicalhumans/

**Comment by tcr** [comment]
Add this as a bullet: Update all email addresses (especially team@technical.io and support@technical.io) to point to @tessel.io addresses. We'll continue to have them work, but I don't want to keep them around.

**Comment by Frijol** [comment]
FB group update: Technical Machine group is changing to Tessel Project. Already in the works, should come through in the next week.

Website: I gave it a pass with https://github.com/technicalmachine/technical-io/pull/334, need to merge & someone else should comb through too to see if there's anything I've missed

**Comment by Frijol** [comment]
Changed our name on Twitter and our Twitter theme color to #f44 just while I was in there.

**Comment by Frijol** [comment]
Ignoring G+ forever. If we want to use the Tessel one we can.

**Comment by Frijol** [comment]
@tcr – do we care enough to change the tumblr name? I know tumblr lets you swap this stuff around without too much fuss, but not sure if it would be a problem for the technical-io integration?

**Comment by Frijol** [comment]
@tcr resolved?
