### ISSUE TITLE
Switch accounts to Zoho Mail

### ISSUE THREAD

**Issue by tcr** [tessel/project#47]
We own the following  email accounts:

* evan@technical.io
* jia@technical.io
* jon@technical.io
* kelsey@technical.io
* ken@technical.io
* kevin@technical.io
* kwyn@technical.io
* e@technical.io

As well as these shell accounts:

* rampart@technical.io
* team@technical.io
* support@technical.io
* quotes@technical.io
* admin@technical.io
* forums@technical.io
* incident@technical.io

Zoho Mail has 10+ free users for one custom domain. From here on out, we should change all technical.io emails to tessel.io.

**Comment by johnnyman727** [comment]
@tcr what's the timeframe on this? We should switch over all @technial related accounts in Mitro.

**Comment by johnnyman727** [comment]
@tcr this was done right? Can we close this issue?

**Comment by Frijol** [comment]
ping @tcr
