### ISSUE TITLE
Open source www.tessel.io

### ISSUE THREAD

**Issue by tcr** [tessel/project#48]
Since most of our web content is now static, we should consider open sourcing the website (even if it remains a dynamic website).

* [x] Carbon copy the current tessel.io website as a new fresh git repo.
* [x] Trim sensitive items and ensure they aren't commited to history.
* [ ] Banner to indicate Tessel's status as an open source project.
* [x] Publish.

**Comment by tcr** [comment]
This should include any of the items from https://github.com/technicalmachine/technical-io/issues/325. (Reminder to self to port those.)

**Comment by Frijol** [comment]
Agreed that we should do this. I think there are already issues on the technical-io repo to this effect. @HarleyKwyn may have something to add to this conversation.

+ OMG Tim review my PR https://github.com/technicalmachine/technical-io/pull/334

**Comment by Frijol** [comment]
opened in https://github.com/tessel/tessel.io
particularly relevant: https://github.com/tessel/tessel.io/issues/6
