### ISSUE TITLE
Switch @technicalhumans and @tesselproject

### ISSUE THREAD

**Issue by tcr** [tessel/project#49]
This will take about five minutes to accomplish.

Having a bot that corrects incorrect mentions is harder. Currently looking if there's any pre-existing demos of this.

**Comment by flaki** [comment]
This might be obvious @tcr, but remember to create a new account for the old handle (technicalhumans) so it can't be misused with all previous static links (e.g: talks/slides) pointing to the old handle.

This also pretty much solves the mention-redirection problem (just log in every now & then, check mentions, or set up email notifications for those - that's the poor man's version, on the long term, this could be automated of course, if needed)

**Comment by Frijol** [comment]
Good thought @flaki! We've been holding off on the name switch until we can set up a bot– the plan is to have one that responds to all @technicalhumans mentions with "Did you mean @tesselproject"? or something to that effect

**Comment by Frijol** [comment]
done!
