### ISSUE TITLE
Agenda for 2015-06-09

### ISSUE THREAD

**Issue by rwaldron** [tessel/project#50]
- Tessel Licenses (@tcr)
- Tessel 2 fritzing component update (@rwaldron)
  - tessel/logos
- Team Outreach (@johnnyman727)
- Hardware Timeline (@tcr)
- Many tasks have no one assigned. How will we address that?
- Yearly budget for web properties. How will payment work for this? How should it be tracked?
- Blog post about RFC, one about Team Members (@frijol)
- Twitter name swapping

**Comment by tcr** [comment]
* @tcr: Adding https://github.com/tessel/project/issues/51 just to make sure we're on the same page.
* @johnnyman727: Update on collaborators and their official capacity.
* @tcr: Brief update on hardware timeline.

**Comment by tcr** [comment]
* @tcr: Many tasks have no one assigned. How will we address that?

**Comment by tcr** [comment]
* @tcr: Yearly budget for web properties

**Comment by Frijol** [comment]
@tcr please merge notes into meetings folder!

**Comment by Frijol** [comment]
@tcr ping

**Comment by tcr** [comment]
This meeting is lost into Slack's history. :(
