### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by tcr** [tessel/project#51]
I propose tessel/licenses to document what licensing we usually go for (and encourage discussion if that's ever an issue). We should also link to appropriate documentation and describe what LICENSE-MIT LICENSE-ASL2 files should exist in properly-licensed repos.

* **MIT/ASL2 for code.** We prefer ASL2 for its patent exception, but we require dual-licensing as MIT is GPL-compatible.
* **[Creative Commons Attribution ShareAlike license](http://creativecommons.org/licenses/by-sa/3.0/)** for Documentation.
* **CC0** for code samples (equivalent to, but technically more correct than "public domain")

Open questions:

* [ ] What did we decide on for hardware licenses? What is our justification? Pinging @kevinmehall @ekolker

**Comment by ekolker** [comment]
Late to the party, but we have "CC-BY-SA and/or Solderpad at your option" on the schematics. The layouts may or may not have such tags attached, but would presumably be the same.

I don't have strong feelings or much knowledge in this area, though... @kevinmehall made most of these calls.

**Comment by kevinmehall** [comment]
CC-BY-SA is very popular for OSHW (e.g. Arduino), but [Creative commons explicitly recommends against its use for hardware](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions).

Solderpad is an adaptation of the Apache 2 license to apply to hardware. Unlike CC-BY-SA and CERN OHL, it doesn't include a copyleft provision (more like ASL2 than GPL). It hasn't seen as much legal review as the common software licenses.

**Comment by tcr** [comment]
Completed by #80.
