### ISSUE TITLE
Links broken in TEAM.md

### ISSUE THREAD

**Issue by andybarry** [tessel/project#59]
The Steering Committee and contribution guide links are giving me 404s on this page:https://github.com/tessel/project/blob/master/TEAM.md

which is linked from here: https://tessel.io/about

**Comment by Frijol** [comment]
Hm, that's weird; I'm having trouble reproducing the issue. Are you able to access that page directly?

**Comment by andybarry** [comment]
67d6398aa342639e3f3dba26cccc5cf69196319c seems to have fixed it.  Thanks!

**Comment by Frijol** [comment]
Oh! I misunderstood before. Thanks for causing me to poke around on that page!
