### ISSUE TITLE
Agenda for 2015-06-30

### ISSUE THREAD

**Issue by rwaldron** [tessel/project#66]
- [x] Are T2's from the 100 batch shipping to pre-orders or is that just the final test batch?
- [x] Update on shipping ETA?
- [x] How many to market?
- [x] Availability moving forward

**Comment by johnnyman727** [comment]
- [ ] Looping back on CLAs with Dojo
- [ ] Looping back on mentorship with new Team Members
- [ ] Development priorities moving forward

**Comment by Frijol** [comment]
Closing, notes are here https://github.com/tessel/project/blob/master/meetings/2015-06-30.md
