### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by Frijol** [tessel/project#73]
What's going on with that?

**Comment by kevinmehall** [comment]
Python is installed in the firmware image. Nothing has been done on libraries or CLI support (and no one is motivated to work on it AFAIK)

**Comment by tcr** [comment]
As of last SC meeting, I'll be heading up the working group on this while we try to find motivated parties.

**Comment by Frijol** [comment]
Not currently in active development. [Read the blog post](https://tessel.io/blog/146714850172/ramping-up-rust-backing-away-from-python-johnny) explaining why.
